# Generated by Django 3.0.5 on 2020-06-15 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TabletAndSteroid',
        ),
    ]
