# Generated by Django 3.0.7 on 2020-06-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scratch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scratch',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='scratch',
            name='time',
            field=models.TimeField(),
        ),
    ]
