# Generated by Django 3.0.7 on 2020-06-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scratch', '0004_auto_20200609_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scratch',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='scratch',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
