# Generated by Django 3.0.5 on 2020-06-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scratch', '0006_dailyscratchcount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyscratchcount',
            name='date',
            field=models.DateField(),
        ),
    ]
