# Generated by Django 3.0.5 on 2020-06-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scratch', '0007_auto_20200613_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyscratchcount',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
