# Generated by Django 3.0.5 on 2020-06-18 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scratch', '0008_auto_20200615_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='NightScratch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_of_10th_scratch', models.CharField(choices=[('before 12am', 'Before 12am'), ('between 12am and 1am', 'Between 12am and 1am'), ('between 1am and 2am', 'Between 1am and 2am'), ('after 2am', 'After 2am')], max_length=22)),
                ('points', models.IntegerField(max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
