# Generated by Django 3.0.5 on 2020-08-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scratch', '0011_auto_20200729_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scratch',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='scratch',
            name='time',
            field=models.TimeField(),
        ),
    ]
