# Generated by Django 3.0.5 on 2020-09-15 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scratch', '0014_scratchmonthlyavg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScratchMonthlyAvg',
        ),
    ]
