# Generated by Django 3.0.5 on 2020-06-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='extra_info',
            field=models.TextField(default='test', max_length=400),
            preserve_default=False,
        ),
    ]
