# Generated by Django 3.0.5 on 2020-06-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_dailyreport_extra_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='extra_info',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
