# Generated by Django 3.0.5 on 2020-07-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20200629_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='scalp_steroid',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
